global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using MarkItDown.Desktop.Models;
global using MarkItDown.Desktop.Services;
global using MarkItDown.Desktop.ViewModels;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
